export declare type LiteralType =
    'ObjectLiteral'
    | 'ArrayLiteral'
    | 'FunctionLiteral'
    | 'NumericLiteral'
    | 'BooleanLiteral'
    | 'StringLiteral'
    | 'NullLiteral'
    | 'UndefinedLiteral'
    | 'RegExpLiteral'